version: '3.4'

services:
  web-app:
    image: ${DOCKER_REGISTRY-}webapplication2
    build:
      context: .
      dockerfile: WebApplication2\Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=http://+:80
    ports:
      - "5000"
    depends_on:
      - nginx-service
  nginx-service:
    build:
      context: .
      dockerfile: nginx\Dockerfile
    ports:
      - "80:80"